export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAILURE = "UPLOAD_VIDEO_FAILURE";

export const POST_RANKING_REQUEST = "POST_RANKING_REQUEST";
export const POST_RANKING_SUCCESS = "POST_RANKING_SUCCESS";
export const POST_RANKING_FAILURE = "POST_RANKING_FAILURE";

export const POST_MATCH_RESULT_REQUEST = "POST_MATCH_REQUEST";
export const POST_MATCH_RESULT_SUCCESS = "POST_MATCH_SUCCESS";
export const POST_MATCH_RESULT_FAILURE = "POST_MATCH_FAILURE";

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const RESET_SUCCESS_MESSAGE = "RESET_SUCCESS_MESSAGE";
